In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
# подготовка данных
import numpy as np
import pandas as pd
import re
import nltk
import string
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [8]:
df = pd.read_csv('/content/drive/MyDrive/reviews.csv', encoding='utf-8', sep='\t')
df.head()

                                              review sentiment
0  качество плохое пошив ужасный (горловина напер...  negative
1  Товар отдали другому человеку, я не получила п...  negative
2  Ужасная синтетика! Тонкая, ничего общего с пре...  negative
3  товар не пришел, продавец продлил защиту без м...  negative
4      Кофточка голая синтетика, носить не возможно.  negative

In [9]:
df['cleaned_reviews'] = df['review'].str.lower() # приведение к нижнему регистру
df['cleaned_reviews'] = df['cleaned_reviews'].str.replace(r'[^\w\s]',' ', regex=True) # удаление пунктуации
df['cleaned_reviews'] = df['cleaned_reviews'].str.replace(r'\d+', '', regex=True) # удаление чисел
# удаление стоп-слов
from nltk.corpus import stopwords
STOPWORDS = set(stopwords.words('russian'))
STOPWORDS -= {"не", "ни", "нет"}
def stopwords(text):
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])
df["cleaned_reviews"] = df["cleaned_reviews"].apply(stopwords)
# удаление эмодзи
def emoji(string):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', string)
#passing the emoji function to 'text_rare'
df['cleaned_reviews'] = df['cleaned_reviews'].apply(emoji)
# удалениe URL
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)
df['cleaned_reviews'] = df['cleaned_reviews'].apply(remove_urls)
df.head()

,review,sentiment,cleaned_reviews
0,качество плохое пошив ужасный (горловина напер...,negative,качество плохое пошив ужасный горловина напере...
1,"Товар отдали другому человеку, я не получила п...",negative,товар отдали другому человеку не получила посы...
2,"Ужасная синтетика! Тонкая, ничего общего с пре...",negative,ужасная синтетика тонкая общего представленной...
3,"товар не пришел, продавец продлил защиту без м...",negative,товар не пришел продавец продлил защиту моего ...
4,"Кофточка голая синтетика, носить не возможно.",negative,кофточка голая синтетика носить не возможно

In [10]:
# токенизация предобработанного текста
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

def tokenize_text(text):
    return nltk.word_tokenize(text)

# сохраним токены (списки слов) в отдельной колонке tokenized_text
df['tokenized_text'] = df['cleaned_reviews'].apply(tokenize_text)
df.head()

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

,review,sentiment,cleaned_reviews,tokenized_text
0,качество плохое пошив ужасный (горловина напер...,negative,качество плохое пошив ужасный горловина напере...,"[качество, плохое, пошив, ужасный, горловина, ..."
1,"Товар отдали другому человеку, я не получила п...",negative,товар отдали другому человеку не получила посы...,"[товар, отдали, другому, человеку, не, получил..."
2,"Ужасная синтетика! Тонкая, ничего общего с пре...",negative,ужасная синтетика тонкая общего представленной...,"[ужасная, синтетика, тонкая, общего, представл..."
3,"товар не пришел, продавец продлил защиту без м...",negative,товар не пришел продавец продлил защиту моего ...,"[товар, не, пришел, продавец, продлил, защиту,..."
4,"Кофточка голая синтетика, носить не возможно.",negative,кофточка голая синтетика носить не возможно,"[кофточка, голая, синтетика, носить, не, возмо..."

In [11]:
# сохраним предобработанные данные в отдельный датафрейм
df_sample = df.groupby('sentiment', group_keys=False).sample(n=5000, random_state=42)
docs = df_sample['tokenized_text'].astype(str).tolist()
df_sample.head()

,review,sentiment,cleaned_reviews,tokenized_text
32308,"Есть зацепки,тонкий Ден.На рост 175 подошло.Од...",neautral,зацепки тонкий ден рост подошло одеть,"[зацепки, тонкий, ден, рост, подошло, одеть]"
52404,одноразовый. не рекомендую,neautral,одноразовый не рекомендую,"[одноразовый, не, рекомендую]"
53397,Платье нормальное.. Но были проблемы с доставк...,neautral,платье нормальное проблемы доставкой вместо об...,"[платье, нормальное, проблемы, доставкой, вмес..."
55058,Время доставки,neautral,время доставки,"[время, доставки]"
32664,Резинка плохо крепится на украшение.После нес...,neautral,резинка плохо крепится украшение нескольких пр...,"[резинка, плохо, крепится, украшение, нескольк..."

In [12]:
!pip install bertopic
from bertopic import BERTopic

topic_model = BERTopic(
    language="multilingual",
    # nr_topics=10,         # сделает тем меньше и крупнее
    # min_topic_size=300,
    calculate_probabilities=True,          # <-- ограничение (укрупнение) тем
    verbose=True
)

topics, probs = topic_model.fit_transform(docs)

Requirement already satisfied: bertopic in /usr/local/lib/python3.12/dist-packages (0.17.4)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.8.41)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.5.11)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.2.3)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (26.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (1.4.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.10.0+cu128)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.15.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (0.24.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.5)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (0.24.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (0.1.2)

2026-02-28 11:15:03,161 - BERTopic - Embedding - Transforming documents to embeddings.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/469 [00:00<?, ?it/s]

2026-02-28 11:15:36,657 - BERTopic - Embedding - Completed ✓
2026-02-28 11:15:36,659 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-02-28 11:16:11,805 - BERTopic - Dimensionality - Completed ✓
2026-02-28 11:16:11,806 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-02-28 11:16:41,076 - BERTopic - Cluster - Completed ✓
2026-02-28 11:16:41,085 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-02-28 11:16:41,395 - BERTopic - Representation - Completed ✓

In [13]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,7612,-1_не_очень_размер_это,"[не, очень, размер, это, продавец, ткань, каче...","[['заказ', 'пришел', 'очень', 'быстро', 'течен..."
1,0,340,0_цвет_цвета_белый_серый,"[цвет, цвета, белый, серый, синий, заказывала,...","[['размер', 'цвет', 'не', 'соответствует'], ['..."
2,1,281,1_хорошее_хорошие_хорошая_хороший,"[хорошее, хорошие, хорошая, хороший, качество,...","[['качество', 'хорошее', 'подошло', 'размер'],..."
3,2,253,2_фото_фотографии_соответствует_видно,"[фото, фотографии, соответствует, видно, факту...","[['фото', 'качество', 'хорошее'], ['ткань', 'н..."
4,3,246,3_ужасное_ужасная_ужасно_ужасный,"[ужасное, ужасная, ужасно, ужасный, ужасные, п...","[['ужасное', 'качество', 'швы', 'материал', 'о..."
...,...,...,...,...,...
177,176,10,176_исправила_задрать_ибанутый_порезы,"[исправила, задрать, ибанутый, порезы, уточнил...","[['доставка', 'быстрая', 'отправка', 'отправко..."
178,177,10,177_коммуникабельный_лепить__сюрпрайз_откащал,"[коммуникабельный, лепить_, сюрпрайз, откащал,...","[['продавец', 'место', 's', 'отправил', 'l', '..."
179,178,10,178_хлопок_жуткая_синтетика_синтетик,"[хлопок, жуткая, синтетика, синтетик, флисовой...","[['это', 'не', 'хлопок', 'синтетика', 'неприят..."
180,179,10,179_воротничок_грязный_трикотаж_качественно,"[воротничок, грязный, трикотаж, качественно, i...","[['качество', 'материала', 'хорошее', 'рисунок..."
181,180,10,180_шарф_залысины_заказа_тянул,"[шарф, залысины, заказа, тянул, отправкой, бра...","[['сказать', 'честно', 'не', 'восторге', 'зака..."

In [14]:
# ключевые слова для темы 1 и их вес
topic_model.get_topic(1)

[('хорошее', np.float64(0.057139159637367196)),
 ('хорошие', np.float64(0.04869999919081548)),
 ('хорошая', np.float64(0.03515133892932456)),
 ('хороший', np.float64(0.02989667948793994)),
 ('качество', np.float64(0.021795456683177037)),
 ('хорошего', np.float64(0.021669071234298627)),
 ('качества', np.float64(0.0122311000257378)),
 ('футболка', np.float64(0.012090616655595845)),
 ('размер', np.float64(0.011946966166300766)),
 ('немного', np.float64(0.011165907854069212))]

In [15]:
# карта дистанций между темами
topic_model.visualize_topics()

In [16]:
# дендрограмма топ-50 тем
topic_model.visualize_hierarchy(top_n_topics=50)

In [17]:
# наиболее значимые слова в топ-5 темах
topic_model.visualize_barchart(top_n_topics=5)

In [18]:
# матрица сходств тем
topic_model.visualize_heatmap(n_clusters=20, width=1000, height=1000)

# **Результаты тематического моделирования**
Для обучения модели было выбрано 5000 отзывов каждого вида: positive, negative и neutral. BERTopic выделил 182 различных темы, однако большое количество документов (7743) не удалось классифицировать ни в одну из конкретных тем. Возможно, на это повлияло моё решение не избавляться от отрицательных частиц "не", "ни" и "нет" во время предобработки, так как они могут существенно поменять смысл написанного.

Тем не менее, модель хорошо справилась с разделением отзывов на темы, часто встречающиеся в отзывах пользователей: цвет (тема 0), соответствие фото (тема 1), размерная сетка (тема 2), возврат и доставка товара (тема 3) и т.д. Поскольку условия задания не предусматривали какие-либо ограничение на количетсво тем, было решено оставить все, в том числе микро-темы.